#!/bin/bash
# fetch-vault-creds.sh
# Fetches scraper credentials from Vaultwarden and writes to .env.scraper
# Run manually or via cron before Docker needs the credentials.
#
# Usage: ./scripts/fetch-vault-creds.sh
# Requires: bw CLI installed, logged in, vault unlocked

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$REPO_DIR/.env.scraper"

echo "Fetching scraper credentials from Vaultwarden..."

# Ensure we have a session
if [ -z "$BW_SESSION" ]; then
    echo "Unlocking vault..."
    export BW_SESSION=$(bw unlock --raw)
fi

# Sync to get latest
bw sync --session "$BW_SESSION" > /dev/null 2>&1

# Fetch Apple credentials
APPLE_USER=$(bw get username "Apple" --session "$BW_SESSION")
APPLE_PASS=$(bw get password "Apple" --session "$BW_SESSION")

if [ -z "$APPLE_USER" ] || [ -z "$APPLE_PASS" ]; then
    echo "ERROR: Failed to fetch Apple credentials"
    exit 1
fi
echo "  ✅ Apple credentials fetched"

# Fetch Synchrony credentials
SYNC_USER=$(bw get username "Synchrony" --session "$BW_SESSION")
SYNC_PASS=$(bw get password "Synchrony" --session "$BW_SESSION")

if [ -z "$SYNC_USER" ] || [ -z "$SYNC_PASS" ]; then
    echo "ERROR: Failed to fetch Synchrony credentials"
    exit 1
fi
echo "  ✅ Synchrony credentials fetched"

# Write to .env.scraper (Docker will read this)
cat > "$ENV_FILE" << EOF
# Auto-generated by fetch-vault-creds.sh — DO NOT COMMIT
SCRAPER_APPLE_USERNAME=$APPLE_USER
SCRAPER_APPLE_PASSWORD=$APPLE_PASS
SCRAPER_SYNCHRONY_USERNAME=$SYNC_USER
SCRAPER_SYNCHRONY_PASSWORD=$SYNC_PASS
EOF

chmod 600 "$ENV_FILE"
echo "  ✅ Written to $ENV_FILE"
echo "Done. Run 'docker compose up -d' to apply."